### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by uvdsl**
Added paper information and additional links.

### CODE REVIEW

**Comment by uvdsl** [comment]
Also, maybe provide first instructions on how many accounts are needed, how to create a offered resource, etc? Or to provide the example resource owner?

Your thoughts?

**Comment by bright-fox** [comment]
Yes, that sounds reasonable. I will come back to those points next week when I find the time!

**Comment by bright-fox** [comment]
> Also, maybe provide first instructions on how many accounts are needed, how to create a offered resource, etc? Or to provide the example resource owner?
> 
> Your thoughts?

Yes, that sounds reasonable. I will come back to those points next week when I find the time!

**Review by bright-fox — COMMENTED** [review]
README will be updated

**Pull request merged**
